version: '3.8'
services:
  modsecurity:
    image: 'owasp/modsecurity-crs:apache'
    hostname: modsecurity.local
    restart: always
    ports:
      - 0.0.0.0:80:80
    tmpfs:
      - /var/tmp:noexec,nosuid,nodev
      - /tmp:noexec,nosuid,nodev
    environment:
      - BACKEND=${BACKEND:-http://10.0.0.100:8800}
      - BACKEND_WS=${BACKEND_WS:-ws://10.0.0.100:8800}
    depends_on:
      - galery
    networks:
      devel:
        ipv4_address: 10.0.0.11

  galery:
    hostname: galery.local
    build:
      context: .
      dockerfile: Dockerfile
    image: 'ghcr.io/redhawkeye/flask-galery:latest'
    restart: always
    depends_on:
      - mysql
    tmpfs:
      - /var/tmp:noexec,nosuid,nodev
      - /tmp:noexec,nosuid,nodev
    volumes:
      - ./galery:/app
    networks:
      devel:
        ipv4_address: 10.0.0.100

  mysql:
    image: 'mysql:8.3.0'
    hostname: mysql.local
    restart: always
    tmpfs:
      - /var/tmp:noexec,nosuid,nodev
      - /tmp:noexec,nosuid,nodev
    environment:
      - MYSQL_DATABASE=${DBNAME:-sawitpro}
      - MYSQL_USER=${DBUSER:-sawitpro}
      - MYSQL_PASSWORD=${DBPASS:-SuperSecretPassword}
      - MYSQL_ROOT_PASSWORD=${DBROOTPASS:-SuperSecretRootPassword}
    volumes:
      - mysql:/var/lib/mysql
    networks:
      devel:
        ipv4_address: 10.0.0.110

networks:
  devel:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1

volumes:
  mysql: {}
