version: '3.8'
services:
  galery:
    hostname: galery.local
    build:
      context: .
      dockerfile: Dockerfile
    image: 'ghcr.io/redhawkeye/flask-galery:latest'
    restart: always
    tmpfs:
      - /var/tmp:noexec,nosuid,nodev
      - /tmp:noexec,nosuid,nodev
    ports:
      - 0.0.0.0:8800:8800
    volumes:
      - ./galery:/app
    networks:
      devel:
        ipv4_address: 10.0.0.100

  mysql:
    image: 'mysql:8.3.0'
    hostname: mysql.local
    restart: always
    tmpfs:
      - /var/tmp:noexec,nosuid,nodev
      - /tmp:noexec,nosuid,nodev
    ports:
      - 0.0.0.0:3306:3306
    environment:
      - MYSQL_DATABASE=${DBNAME:-sawitpro}
      - MYSQL_USER=${DBUSER:-sawitpro}
      - MYSQL_PASSWORD=${DBPASS:-SuperSecretPassword}
      - MYSQL_ROOT_PASSWORD=${DBROOTPASS:-SuperSecretRootPassword}
    volumes:
      - mysql:/var/lib/mysql
    networks:
      devel:
        ipv4_address: 10.0.0.110

networks:
  devel:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1

volumes:
  mysql: {}
